### ISSUE TITLE
dafruit_bus_device.i2c_device' has no attribute 'I2CDevice'

### ISSUE THREAD

**Issue by shanepisko** [adafruit/Adafruit_CircuitPython_BusDevice#49]
Traceback (most recent call last):
  File "robot.py", line 8, in <module>
    kit = MotorKit()
  File "/usr/local/lib/python3.5/dist-packages/adafruit_motorkit.py", line 76, in __init__
    self._pca = PCA9685(i2c, address=address)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_pca9685.py", line 137, in __init__
    self.i2c_device = i2c_device.I2CDevice(i2c_bus, address)
AttributeError: module 'adafruit_bus_device.i2c_device' has no attribute 'I2CDevice'

**Comment by ladyada** [comment]
hi for tech support please post in the adafruit circuitpython forums.
