### ISSUE TITLE
i2c_device  __init__ error

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_BusDevice#9]
line 56 of  i2c_device.py   in "__init__" results in an error:
calling  i2c.writeto(device_address,b'')
causes the error.
```
Adafruit CircuitPython 2.1.0-3-gbd7abcd on 2017-10-27; Adafruit Metro M0 Express with samd21g18
>>> 
>>> import mcp9808_test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mcp9808_test.py", line 10, in <module>
  File "mcp9808_test.py", line 8, in <module>
  File "libraries/drivers/mcp9808/adafruit_mcp9808.py", line 66, in __init__
  File "libraries/helpers/bus_device/adafruit_bus_device/i2c_device.py", line 60, in __init__
  File "libraries/helpers/bus_device/adafruit_bus_device/i2c_device.py", line 58, in __init__
  File "libraries/helpers/bus_device/adafruit_bus_device/i2c_device.py", line 56, in __init__
ValueError: Buffer must be at least length 1
```
It is isolated here:
```
Adafruit CircuitPython 2.1.0-3-gbd7abcd on 2017-10-27; Adafruit Metro M0 Express with samd21g18
>>>
>>>
>>> from board import SCL,SDA
>>> from busio import I2C
>>> from adafruit_bus_device.i2c_device import I2CDevice
>>> i2c=I2C(SCL,SDA)
>>> i2c.try_lock()
True
>>> i2c.writeto(0x18,b'')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Buffer must be at least length 1
```

**Comment by dhalbert** [comment]
Fixed by #387. Write of zero-length buffers is now allowed again.
